### ISSUE TITLE
NoteSynthesizer.py:108: RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by asigalov61** [hmartelb/NSynth-MIDI-Renderer#1] opened 2021-05-19 07:04 UTC
NoteSynthesizer.py:108: RuntimeWarning: invalid value encountered in true_divide
  data /= np.max(np.abs(data))

If you can help, I would really appreciate it.

Thank you.

**Comment by hmartelb** [comment] 2021-05-19 07:42
This happens because your resulting audio is silence. The normalization takes the max value (which is zero) and you get the error. 

Check the following:
1) Do you really want a silence segment? If so, add a small epsilon value: max -> max + eps, where eps = 1e-9 for example. 

2) Is the path to the NSynth dataset correct? Can you load the audio of individual notes? If you can't, that's why you get silence. 

3) Does the midi sequence contain notes? You may get the error because the sequence is empty and the data is all zeros. 

Let me know if it helps to close the issue. Regards.

**Comment by asigalov61** [comment] 2021-05-19 07:55
Thank you for your quick response.

I have checked everything and I followed instructions on the repo page but it just does not work. I could not find the problem.

Can you take a look at the colab?

Thank you

https://colab.research.google.com/drive/1PmD7IK6FG3IkeHT5-wasSZVPADDm2Lt2?usp=sharing

**Comment by hmartelb** [comment] 2021-05-19 10:10
The notebook takes too long because of the NSynth download, which I have on my machine already. I revised the code and did some modifications. It can also be due to the dependencies, so I added the requirements.txt (were missing before). 

Now it works fine when I execute as in the instructions.
`python NoteSynthesizer.py --db ..\NSynth\Train\audio --seq midi\bach_847.mid --output example.wav`

Please get the latest version of the code and try again. Let me know if it works this time. 
Regards.

**Comment by asigalov61** [comment] 2021-05-19 11:04
Yes, thank you for your prompt support!. Yes, it seems that it was a dependency issue. Now it seem to at least load the dataset...

But I still get the following errors and the empty output WAV. I did install the code from your updated version but it still does not work. :(

/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
Notes loaded
Note not fonund guitar_acoustic_000-066-050.wav
Note not fonund guitar_acoustic_000-057-050.wav
Note not fonund guitar_acoustic_000-071-050.wav
Note not fonund guitar_acoustic_000-079-100.wav
Note not fonund guitar_acoustic_000-049-050.wav

**Comment by hmartelb** [comment] 2021-05-19 13:57
Ok, I think more details may be needed to reproduce it. All I can say for now is that I tested on Python 3.6, with the requirements.txt and it doesn't show the PySoundFile warnings. Try downgrading or fix the dependencies to your own needs. 

Other reasons may be that the MIDI file contains notes that do not exist in the original NSynth directory. Please check as well. 
I close the issue as it is no longer related to the original problem.
Regards.

**Closed as completed by hmartelb** 2021-05-19 13:57 UTC

**Comment by asigalov61** [comment] 2021-05-19 14:50
Thank you very much for your help and support, Hector. Much appreciated.

I will try to troubleshoot and I hope it will work. Maybe it is just a Colab issue. 

Thank you again.

Alex

**Comment by asigalov61** [comment] 2021-05-19 15:32
Update: GOT IT TO WORK :) It was definitely dependencies hell and also maybe Google colab was acting up due to a huge dataset.

/content/NSynth-MIDI-Renderer
Preloading notes for keyboard_acoustic_000
Notes loaded
Saving audio output to /content/RENDER.WAV

Anyway, thank you again for your support. :)

**Comment by hmartelb** [comment] 2021-05-19 15:48
Glad to know it worked! :)
